package greetingApp;


/**
* greetingApp/GreetingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from greeting.idl
* Thursday, March 19, 2020 10:04:51 AM CET
*/

public interface GreetingOperations 
{
  String hi ();
  void shutdown ();
} // interface GreetingOperations
