package greetingApp;


/**
* greetingApp/GreetingPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from greeting.idl
* Thursday, March 19, 2020 10:04:51 AM CET
*/

public abstract class GreetingPOA extends org.omg.PortableServer.Servant
 implements greetingApp.GreetingOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("hi", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // greetingApp/Greeting/hi
       {
         String $result = null;
         $result = this.hi ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // greetingApp/Greeting/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:greetingApp/Greeting:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Greeting _this() 
  {
    return GreetingHelper.narrow(
    super._this_object());
  }

  public Greeting _this(org.omg.CORBA.ORB orb) 
  {
    return GreetingHelper.narrow(
    super._this_object(orb));
  }


} // class GreetingPOA
