package greetingApp;


/**
* greetingApp/Greeting.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from greeting.idl
* Thursday, March 19, 2020 10:04:51 AM CET
*/

public interface Greeting extends GreetingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Greeting
